adding ja - initial

diff --git a/bin/install-mecab b/bin/install-mecab
--- a/bin/install-mecab
+++ b/bin/install-mecab
@@ -1,15 +1,21 @@
 #! /bin/bash
+LANG_DIC="ko" #default ja
+[ -n "$1" ] && LANG_DIC="$1"
+DIR_BASE="mecab_${LANG_DIC}"
 
-if [ $# == 1 ] && [ $1 == "ko" ]; then
+if [ "$LANG_DIC" == "ko" ]; then
     URL_MECAB=https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
     URL_MECAB_DIC=https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.0.1-20150920.tar.gz
     DIR_MECAB=mecab-0.996-ko-0.9.2
     DIR_MECAB_DIC=mecab-ko-dic-2.0.1-20150920
-else
-    URL_MECAB=http://mecab.googlecode.com/files/mecab-0.996.tar.gz
-    URL_MECAB_DIC=http://mecab.googlecode.com/files/mecab-ipadic-2.7.0-20070801.tar.gz
+elif [ "$LANG_DIC" == "ja" ]; then
+    URL_MECAB=https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE
+    URL_MECAB_DIC=https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM
     DIR_MECAB=mecab-0.996
     DIR_MECAB_DIC=mecab-ipadic-2.7.0-20070801
+else
+  echo "Error: unknown LANG: ${LANG_DIC}"
+  exit 1;
 fi
 
 cd `dirname $0`/../
@@ -23,7 +29,7 @@ cd $BUILD_PATH
 curl -OL $URL_MECAB
 tar xfz $DIR_MECAB.tar.gz
 cd $DIR_MECAB
-./configure --prefix=$PROJECT_HOME/mecab
+./configure --prefix=$PROJECT_HOME/${DIR_BASE}
 make
 make install
 
@@ -32,9 +38,9 @@ cd $BUILD_PATH
 curl -OL $URL_MECAB_DIC
 tar xfz $DIR_MECAB_DIC.tar.gz
 cd $DIR_MECAB_DIC
-export PATH=$PROJECT_HOME/mecab/bin:$PATH
+export PATH=$PROJECT_HOME/${DIR_BASE}/bin:$PATH
 ./autogen.sh
-./configure --prefix=$PROJECT_HOME/mecab
+./configure --prefix=$PROJECT_HOME/${DIR_BASE}
 make
 make install
 
